### ISSUE TITLE
Wondering ...proxy error ...what is misstng??

### ISSUE THREAD

**Issue by unixbhaskar** [perlancar/perl-App-org2wp#1]
Precisely..

org2wp: ERROR 500: Died: proxy: transport protocol not specified

**Comment by perlancar** [comment]
I just used `org2wp` today to post to https://perlancar.wordpress.com/2022/05/01/list-of-new-cpan-distributions-apr-2022/ so it still works at least in my case, to wordpress.com. 

What did you set your proxy to? (in `--proxy` command-line option or `proxy` configuration parameter)?

Also what OS are you using? Do you by any chance set `http_proxy` or `HTTP_PROXY` environment variable?

**Comment by unixbhaskar** [comment]
> I just used `org2wp` today to post to https://perlancar.wordpress.com/2022/05/01/list-of-new-cpan-distributions-apr-2022/ so it still works at least in my case, to wordpress.com.
> 
> What did you set your proxy to? (in `--proxy` command-line option or `proxy` configuration parameter)?
> 
> Also what OS are you using? Do you by any chance set `http_proxy` or `HTTP_PROXY` environment variable?

In fact , I am not using proxy at all. 

I have a config file related to org2wp  as mentioned somewhere ..just 3 lines in it 

proxy=" the url to the xmlrpc of wordpress"
username "my username"
password=" password"

..that all. I was wondering , why do I need proxy? How Can I do that without proxy? 

I am exclusive on GNU/Linux(Gentoo, Slackware, Debian ...doesn't matter really....I have a common home...and that config file resides there) 

Sidenote....I look into your code and install several module by cpan shell.....in spite of that ...I am getting this ...

I must be doing or missing something very obvious. ...alas! couldn't figure it out. 

That damn proxy thing is hindering......

**Comment by perlancar** [comment]
The `proxy` term is a bit unfortunate. It has nothing to do with HTTP/HTTPS proxy but it means the XML-RPC server endpoint URL. This term is used by XMLRPC::Lite and SOAP::Lite, and I'm simply using the same terminology.

Could you share the exact config you have (redacting the sensitive information like user/pasas of course). I suspect in:

    proxy=" the url to the xmlrpc of wordpress"

you might have an extra space after the first double quote. The double quote is not necessary, for the most part.

**Comment by unixbhaskar** [comment]
> you might have an extra space after the first double quote. The double quote is not necessary, for the most part.

   ```
proxy=>"https://unixbhaskar.wordpress.com/xmlrpc.php",
    username=>"my_username",
    password=>"password",
```
The only visible change I made in the first line from "=" to "=>" ...otherwise that complaint. But I can revert if you find else I messed up. ...oh and the double-quote surrounds them...I got the same error without them too ...

**Comment by perlancar** [comment]
> The only visible change I made in the first line from "=" to "=>" ...otherwise that complaint. But I can revert if you find else I messed up. ...oh and the double-quote surrounds them...I got the same error without them too ...

Ok there you have it. The configuration is in INI format, not Perl. You can see using:

    % PERINCI_CMDLINE_PLUGINS=-Debug::DumpArgs org2wp ...

the script will show that `proxy` will have the value of something like:

    >"https://blah",

instead of what you want:

    http://blah

**Comment by unixbhaskar** [comment]
> 

I am so sorry ...I failed to follow you. What exactly I have to change? Without that Perl notation, I mean when it was only = still it was throwing errors. 
Can tell me verbatim what exactly I need to put in that damn conf file????

**Comment by unixbhaskar** [comment]
Made some progress after installing a plethora of stuff .....but again stuck at her e

`org2wp: ERROR 500: Died: 404 Not Found at /usr/share/perl5/site_perl/App/org2wp.pm line 441`

....and that line 441 pointing to Category.....wondering ...

Now, debug statement you gave ...and I ran it ...produces this 

`PERINCI_CMDLINE_PLUGINS=-Debug::DumpArgs org2wp testcli.org`

```
-orig_comment_status => "closed",                                        # { 0}
  -orig_filename       => "testcli.org",                                   # { 1}
-orig_proxy          => "https://unixbhaskar.wordpress.com/xmlrpc.php,", # { 3}
  -orig_username       => ">\"unixbhaskar\",",                             # { 4}
  -set_comment_status  => 1,                                               # { 5}
  -set_filename        => 1,                                               # { 6}
  -set_password        => 1,                                               # { 7}
  -set_proxy           => 1,                                               # { 8}
  -set_username        => 1,                                               # { 9}
  comment_status       => "closed",                                        # {10}
  filename             => "testcli.org",                                   # {11}
proxy                => "https://unixbhaskar.wordpress.com/xmlrpc.php,", # {13}
  username             => ">\"unixbhaskar\",",                             # {14}
```

I have removed the password field from this pasting ....

**Comment by perlancar** [comment]
Are you familiar with INI format? The parameter line is just:

    param=value

or:

    param="value"

and not any of these:

    param = value,
    param => value,
    param => "value"
    param => "value",

Please don't use arrow (`=>`), just use equal sign (`=`). Don't use comma at the end. From the debug output I see that you still use trailing comma for the proxy, and arrow for the username and perhaps the password.

**Comment by unixbhaskar** [comment]
> Are you familiar with INI format? The parameter line is just:
> 
> ```
> param=value
> ```
> 
> or:
> 
> ```
> param="value"
> ```
> 
> and not any of these:
> 
> ```
> param = value,
> param => value,
> param => "value"
> param => "value",
> ```
> 
> Please don't use arrow (`=>`), just use equal sign (`=`). Don't use comma at the end. From the debug output I see that you still use trailing comma for the proxy, and arrow for the username and perhaps the password.

Thanks for your patience. Now , it is working ....followed your words ...closing this .
